CREATE TABLE TB_PRODUCT (
	ID BIGINT NOT NULL,
	NAME VARCHAR(50) NOT NULL,
	CODE VARCHAR(50) NOT NULL,
	CONSTRAINT PK_ID_PRODUCT PRIMARY KEY(ID)
);


CREATE SEQUENCE SQ_PRODUCT
START 1
INCREMENT 1
OWNED BY TB_PRODUCT.ID;


INSERT INTO TB_PRODUCT (ID, NAME, CODE)
VALUES (NEXTVAL('SQ_PRODUCT'), 'PRODUCT', '1');


SELECT * FROM TB_PRODUCT;